# Generated by Django 5.0.1 on 2025-01-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_admin_dashboard', 'Can view admin dashboard'), ('manage_categories', 'Can manage financial categories'), ('view_user_statistics', 'Can view user statistics and analytics'), ('manage_own_finances', 'Can manage own financial data')]},
        ),
    ]
