# Generated by Django 5.1.4 on 2024-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcategory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
