# Generated by Django 5.1.4 on 2025-01-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_category', '0006_futuresaving'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
