# Generated by Django 5.1.4 on 2025-01-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_category', '0007_debt_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
